"""first revision

Revision ID: 79ce12318ea5
Revises: 
Create Date: 2024-02-07 10:51:21.126182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79ce12318ea5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('driver_licence_number', sa.String(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('working', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_birth_date'), 'driver', ['birth_date'], unique=False)
    op.create_index(op.f('ix_driver_driver_licence_number'), 'driver', ['driver_licence_number'], unique=False)
    op.create_index(op.f('ix_driver_expiry_date'), 'driver', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_driver_first_name'), 'driver', ['first_name'], unique=False)
    op.create_index(op.f('ix_driver_id'), 'driver', ['id'], unique=False)
    op.create_index(op.f('ix_driver_last_name'), 'driver', ['last_name'], unique=False)
    op.create_index(op.f('ix_driver_working'), 'driver', ['working'], unique=False)
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('license_plate', sa.String(), nullable=False),
    sa.Column('manufacture_year', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_active'), 'vehicle', ['active'], unique=False)
    op.create_index(op.f('ix_vehicle_id'), 'vehicle', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_license_plate'), 'vehicle', ['license_plate'], unique=False)
    op.create_index(op.f('ix_vehicle_manufacture_year'), 'vehicle', ['manufacture_year'], unique=False)
    op.create_table('session',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('session_start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('login_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('logout_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_driver_id'), 'session', ['driver_id'], unique=False)
    op.create_index(op.f('ix_session_id'), 'session', ['id'], unique=False)
    op.create_index(op.f('ix_session_login_time'), 'session', ['login_time'], unique=False)
    op.create_index(op.f('ix_session_logout_time'), 'session', ['logout_time'], unique=False)
    op.create_index(op.f('ix_session_session_end_time'), 'session', ['session_end_time'], unique=False)
    op.create_index(op.f('ix_session_session_start_time'), 'session', ['session_start_time'], unique=False)
    op.create_index(op.f('ix_session_vehicle_id'), 'session', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_vehicle_id'), table_name='session')
    op.drop_index(op.f('ix_session_session_start_time'), table_name='session')
    op.drop_index(op.f('ix_session_session_end_time'), table_name='session')
    op.drop_index(op.f('ix_session_logout_time'), table_name='session')
    op.drop_index(op.f('ix_session_login_time'), table_name='session')
    op.drop_index(op.f('ix_session_id'), table_name='session')
    op.drop_index(op.f('ix_session_driver_id'), table_name='session')
    op.drop_table('session')
    op.drop_index(op.f('ix_vehicle_manufacture_year'), table_name='vehicle')
    op.drop_index(op.f('ix_vehicle_license_plate'), table_name='vehicle')
    op.drop_index(op.f('ix_vehicle_id'), table_name='vehicle')
    op.drop_index(op.f('ix_vehicle_active'), table_name='vehicle')
    op.drop_table('vehicle')
    op.drop_index(op.f('ix_driver_working'), table_name='driver')
    op.drop_index(op.f('ix_driver_last_name'), table_name='driver')
    op.drop_index(op.f('ix_driver_id'), table_name='driver')
    op.drop_index(op.f('ix_driver_first_name'), table_name='driver')
    op.drop_index(op.f('ix_driver_expiry_date'), table_name='driver')
    op.drop_index(op.f('ix_driver_driver_licence_number'), table_name='driver')
    op.drop_index(op.f('ix_driver_birth_date'), table_name='driver')
    op.drop_table('driver')
    # ### end Alembic commands ###
