"""remove login logout time field in session table

Revision ID: 85f2cc115450
Revises: 79ce12318ea5
Create Date: 2024-02-07 11:35:32.453371

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '85f2cc115450'
down_revision = '79ce12318ea5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_session_login_time', table_name='session')
    op.drop_index('ix_session_logout_time', table_name='session')
    op.drop_column('session', 'login_time')
    op.drop_column('session', 'logout_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('logout_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('session', sa.Column('login_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.create_index('ix_session_logout_time', 'session', ['logout_time'], unique=False)
    op.create_index('ix_session_login_time', 'session', ['login_time'], unique=False)
    # ### end Alembic commands ###
